Added function to allow dynamic logging configuration using a provided dictionary.
dotimplement/HealthChain pull request #82
Opened 2024-10-09 22:16 UTC by RINO-GAELICO

## Description

Added a `configure_logging` function that allows users to set up logging configurations dynamically. This function can accept a configuration dictionary, enabling users to adjust log levels, formats, and handlers. If no configuration is provided, it defaults to a basic logging setup with INFO level logging.

## Related Issue

#32

## Changes Made

- Implemented the `configure_logging` function in the relevant module.
- Added documentation for the function, including parameter descriptions and usage examples.
- Updated the logging initialization to use the new configuration function, enhancing logging flexibility.

## Testing

I didn't add a test since a test for start_sandbox function is still missing.

## Checklist

- [X] I have read the [contributing](https://github.com/dotimplement/HealthChain/CONTRIBUTING.md) guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Additional Notes

2024-10-10 13:48 UTC, jenniferjiangkells submitted a review, later dismissed

2024-10-13 10:02 UTC, adamkells requested changes
Hi @RINO-GAELICO , this looks great! I think it would just be a bit neater if we move the logging code to be inside the start_sandbox function and pass the logging_config directly in there rather than having a separate function for it.

2024-10-15 01:00 UTC, RINO-GAELICO commented
@adamkells thanks for the feedback. Here is the updated code. Please let me know if everything looks ok

2024-10-15 11:41 UTC, adamkells approved these changes
Looks great! Will merge shortly

2024-10-15 11:42 UTC, merged